### ISSUE TITLE
Can't handle 2fa strings from Amazon

### ISSUE THREAD

**Issue by adsbenham** [rsc/2fa#9] opened 2018-10-31 16:12 UTC
I have 2fa working beautifully with a number of web sites - with the exception on Amazon.  I get a base32 error when attempting to add an account:

$ 2fa -add amazon
2fa key for amazon: WUBY 64EK TZIQ J3GI ICIM VAI7 QOL6 VNHM NLAJ 2JMZ UGBN HXGZ 66EA
2fa: invalid key: illegal base32 data at input byte 48

Try without spaces:

$ 2fa -add amazon
2fa key for amazon: WUBY64EKTZIQJ3GIICIMVAI7QOL6VNHMNLAJ2JMZUGBNHXGZ66EA
2fa: invalid key: illegal base32 data at input byte 48

Let's get a new key:
$ 2fa -add amazon
2fa key for amazon: 6SDT TM7L B4SB D4FH V2RJ O67F LTB2 N4JH 3OAS JAB4 T427 ZOSS 67UQ
2fa: invalid key: illegal base32 data at input byte 48

I can add the keys to an Android device running Google Authenticator...

**Comment by rsc** [comment] 2019-08-21 15:18
Sorry for not seeing this earlier, but this seems to be a duplicate of #4, which was fixed in January 2018.

**Closed by rsc** 2019-08-21 15:18 UTC
